config/routes.rb
Rails.application.routes.draw do
  resources :comment_likes
  resources :posts
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment_like.rb
class CommentLike < ApplicationRecord
  belongs_to :user
  belongs_to :post

  scope :likes, -> { where("record_type = 'like'") }
  scope :comments, -> { where("record_type = 'comment'") }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :posts,    dependent: :destroy
  has_many :comment_likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comment_likes_controller.rb
class CommentLikesController < ApplicationController
  before_action :set_comment_like, only: %i[ show edit update destroy ]

  # GET /comment_likes or /comment_likes.json
  def index
    @comment_likes = CommentLike.all
  end

  # GET /comment_likes/1 or /comment_likes/1.json
  def show
  end

  # GET /comment_likes/new
  def new
    @comment_like = CommentLike.new
  end

  # GET /comment_likes/1/edit
  def edit
  end

  # POST /comment_likes or /comment_likes.json
  def create
    @comment_like = CommentLike.new(comment_like_params)

    respond_to do |format|
      if @comment_like.save
        format.html { redirect_to @comment_like, notice: "Comment like was successfully created." }
        format.json { render :show, status: :created, location: @comment_like }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment_like.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comment_likes/1 or /comment_likes/1.json
  def update
    respond_to do |format|
      if @comment_like.update(comment_like_params)
        format.html { redirect_to @comment_like, notice: "Comment like was successfully updated." }
        format.json { render :show, status: :ok, location: @comment_like }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment_like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comment_likes/1 or /comment_likes/1.json
  def destroy
    @comment_like.destroy
    respond_to do |format|
      format.html { redirect_to comment_likes_url, notice: "Comment like was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment_like
      @comment_like = CommentLike.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_like_params
      params.require(:comment_like).permit(:comment, :like, :record_type, :user_id, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:description, :user_id, :image)
    end
end
rails generate model comment_like comment:text like:boolean type:string user:references post:references 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_likes_helper.rb
module CommentLikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comment_likes/_form.html.erb
<%= form_with(model: comment_like, local: true) do |form| %>
  <% if comment_like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment_like.errors.count, "error") %> prohibited this comment_like from being saved:</h2>

      <ul>
        <% comment_like.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="field">
    <%= form.label :like %>
    <%= form.check_box :like %>
  </div>

  <div class="field">
    <%= form.label :record_type %>
    <%= form.text_field :record_type %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :post_id %>
    <%= form.text_field :post_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comment_likes/edit.html.erb
<h1>Editing Comment Like</h1>

<%= render 'form', comment_like: @comment_like %>

<%= link_to 'Show', @comment_like %> |
<%= link_to 'Back', comment_likes_path %>

app/views/comment_likes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comment Likes</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>Like</th>
      <th>Record type</th>
      <th>User</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comment_likes.each do |comment_like| %>
      <tr>
        <td><%= comment_like.comment %></td>
        <td><%= comment_like.like %></td>
        <td><%= comment_like.record_type %></td>
        <td><%= comment_like.user_id %></td>
        <td><%= comment_like.post_id %></td>
        <td><%= link_to 'Show', comment_like %></td>
        <td><%= link_to 'Edit', edit_comment_like_path(comment_like) %></td>
        <td><%= link_to 'Destroy', comment_like, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment Like', new_comment_like_path %>

app/views/comment_likes/new.html.erb
<h1>New Comment Like</h1>

<%= render 'form', comment_like: @comment_like %>

<%= link_to 'Back', comment_likes_path %>

app/views/comment_likes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @comment_like.comment %>
</p>

<p>
  <strong>Like:</strong>
  <%= @comment_like.like %>
</p>

<p>
  <strong>Record type:</strong>
  <%= @comment_like.record_type %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment_like.user_id %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment_like.post_id %>
</p>

<%= link_to 'Edit', edit_comment_like_path(@comment_like) %> |
<%= link_to 'Back', comment_likes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyInsta</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.description %></td>
        <td><%= post.user_id %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @post.image %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>